language: ruby
rvm:
  - 2.4.1
branches:
  only:
  - master
  - production
before_install:
# Use travisqueue to manage build concurrency.
- ./scripts/travisqueue.sh install
- ./scripts/travisqueue.sh start
# Install required tools.
# pulumi
- curl -L https://get.pulumi.com/ | bash -s -- --version 0.16.6-dev.1543332884
- export PATH=$PATH:$HOME/.pulumi/bin
# Remove after pulumi/pulumi/issues/2203 is resolved.
- export PULUMI_RECORD_ENGINE_EVENTS=1
# yarn
- npm i -g yarn
# Work around a current issue in bundler. See:
# https://github.com/travis-ci/travis-ci/issues/8969
- gem update --system
- gem install bundler
script:
- echo "TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE}"
- make travis_${TRAVIS_EVENT_TYPE}
after_script:
- ./scripts/travisqueue.sh finish
notifications:
  webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
