sass:
    style: compressed

plugins:
  - jekyll-octicons
  - kramdown
  - jekyll-include-cache # used for recursive loop in _includes/tree.html
  - jekyll-redirect-from # for 301 redirects
  - jekyll-relative-links # to convert internal MD links to HTML
  - jekyll-optional-front-matter # for Markdown without front matter (e.g., CLI reference)

markdown: kramdown
kramdown:
  parse_block_html: false

optional_front_matter:
  remove_originals: true

relative_links:
  enabled: true
  collections: true

# Files to not include when building.
exclude:
  - .gitattributes
  - .gitignore
  - .travis.yml
  - infrastructure
  - Gemfile
  - Gemfile.lock
  - Makefile
  - package.json
  - README.md
  - scripts
  - vendor
  - yarn.lock

# Tables of contents, stored in the _data folder, that control the sidebar nav
# To add a new entry to the table of contents, create a new doc in the appropriate folder,
# then add an entry in _data/<toc>.yaml. 
# Ensure that the ordering matches the logical flow that customers expect
tocs:
  - home
  - install
  - quickstart
  - tour
  - reference

# By default, use a `default_toc` layout, that shows a table of contents on the left
defaults:
  - values:
      layout: default_toc
